# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: original

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: double-quote-string-fixer
      - id: check-yaml
      # - id: check-added-large-files
      - id: requirements-txt-fixer
      # - id: name-tests-test
      #   args: ["--django"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: isort
        name: Run isort
        entry: uv run isort
        language: system
        args: ["--profile", "google", "--filter-files"]
        types: [file, python]
      - id: black
        name: Run black
        entry: uv run black
        language: system
        types: [file, python]
      - id: flake8
        name: Run flake8
        entry: uv run flake8
        language: system
        types: [file, python]
      - id: mypy
        name: Run mypy
        entry: uv run mypy
        language: system
        types: [file, python]
      - id: pyupgrade
        name: Run pyupgrade
        entry: uv run pyupgrade
        language: system
        args: ["--py310-plus"]
        types: [file, python]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  # - repo: https://github.com/pylint-dev/pylint
  #   rev: v2.17.2
  #   hooks:
  #     - id: pylint
