"""Property values for search query methods.

This enum is used by the ``search`` method in both sync and async
clients to specify which properties to include in search results.
The ``srprop`` parameter is deprecated upstream but still supported.
"""

from enum import Enum
from typing import Union


class SearchProp(Enum):
    """Property values for search query methods.

    This enum is used by the ``search`` method in both sync and async
    clients to specify which properties to include in search results.
    The ``srprop`` parameter is deprecated upstream but still supported.
    """

    SIZE = "size"
    """Adds the size of the page in bytes."""
    WORDCOUNT = "wordcount"
    """Adds the word count of the page."""
    TIMESTAMP = "timestamp"
    """Adds the timestamp of when the page was last edited."""
    SNIPPET = "snippet"
    """Adds a snippet of the page with query term highlighting markup."""
    TITLE_SNIPPET = "titlesnippet"
    """Adds the page title with query term highlighting markup."""
    REDIRECT_TITLE = "redirecttitle"
    """Adds the title of the matching redirect."""
    REDIRECT_SNIPPET = "redirectsnippet"
    """Adds the title of the matching redirect with highlighting."""
    SECTION_TITLE = "sectiontitle"
    """Adds the title of the matching section."""
    SECTION_SNIPPET = "sectionsnippet"
    """Adds the title of the matching section with highlighting."""
    IS_FILE_MATCH = "isfilematch"
    """Adds a boolean indicating if the search matched file content."""
    CATEGORY_SNIPPET = "categorysnippet"
    """Adds the matching category name with highlighting."""
    SCORE = "score"
    """Relevance score (deprecated upstream, ignored)."""
    HAS_RELATED = "hasrelated"
    """Has related suggestions (deprecated upstream, ignored)."""
    EXTENSION_DATA = "extensiondata"
    """Adds extra data generated by extensions."""


#: Type alias for search property arguments.
#: Accepts either a :class:`SearchProp` enum member or a raw ``str``.
#: e.g. ``SearchProp.SIZE`` or simply ``"size"``.
WikiSearchProp = Union[SearchProp, str]


def search_prop2str(prop: WikiSearchProp) -> str:
    """
    Convert a :class:`WikiSearchProp` value to a plain ``str``.

    If *prop* is a :class:`SearchProp` enum member its string value
    is returned.  If it is already a ``str`` it is returned unchanged.

    :param prop: search property to convert
    :return: string representation of the search property

    **Examples:**

    .. code-block:: python

        from wikipediaapi import search_prop2str, SearchProp

        # Convert enum to string
        assert search_prop2str(SearchProp.SIZE) == "size"
        assert search_prop2str(SearchProp.WORDCOUNT) == "wordcount"
        assert search_prop2str(SearchProp.TIMESTAMP) == "timestamp"
        assert search_prop2str(SearchProp.SNIPPET) == "snippet"
        assert search_prop2str(SearchProp.TITLE_SNIPPET) == "titlesnippet"
        assert search_prop2str(SearchProp.REDIRECT_TITLE) == "redirecttitle"
        assert search_prop2str(SearchProp.REDIRECT_SNIPPET) == "redirectsnippet"
        assert search_prop2str(SearchProp.SECTION_TITLE) == "sectiontitle"
        assert search_prop2str(SearchProp.SECTION_SNIPPET) == "sectionsnippet"
        assert search_prop2str(SearchProp.IS_FILE_MATCH) == "isfilematch"
        assert search_prop2str(SearchProp.CATEGORY_SNIPPET) == "categorysnippet"
        assert search_prop2str(SearchProp.SCORE) == "score"
        assert search_prop2str(SearchProp.HAS_RELATED) == "hasrelated"
        assert search_prop2str(SearchProp.EXTENSION_DATA) == "extensiondata"

        # String pass-through (unchanged)
        assert search_prop2str("size") == "size"
        assert search_prop2str("wordcount") == "wordcount"
        assert search_prop2str("timestamp") == "timestamp"
        assert search_prop2str("snippet") == "snippet"
        assert search_prop2str("titlesnippet") == "titlesnippet"
        assert search_prop2str("redirecttitle") == "redirecttitle"
        assert search_prop2str("redirectsnippet") == "redirectsnippet"
        assert search_prop2str("sectiontitle") == "sectiontitle"
        assert search_prop2str("sectionsnippet") == "sectionsnippet"
        assert search_prop2str("isfilematch") == "isfilematch"
        assert search_prop2str("categorysnippet") == "categorysnippet"
        assert search_prop2str("score") == "score"
        assert search_prop2str("hasrelated") == "hasrelated"
        assert search_prop2str("extensiondata") == "extensiondata"

        # Custom values pass through
        assert search_prop2str("custom") == "custom"
    """
    if isinstance(prop, SearchProp):
        return prop.value

    return prop
